services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    # depends_on:
      # - delivery-service
      # - order-service
      # - restaurant-service
      # - user-service

  # delivery-service:
  #   build: ./services/delivery-service
  #   container_name: delivery-service
  #   ports:
  #     - "5003:5003"
  #   env_file:
  #     - ./services/delivery-service/.env
  #   depends_on:
  #     - mongo

  # order-service:
  #   build: ./services/order-service
  #   container_name: order-service
  #   ports:
  #     - "5002:5002"
  #   env_file:
  #     - ./services/order-service/.env
  #   depends_on:
  #     - mongo

  # restaurant-service:
  #   build: ./services/restaurant-service
  #   container_name: restaurant-service
  #   ports:
  #     - "5001:5001"
  #   env_file:
  #     - ./services/restaurant-service/.env
  #   depends_on:
  #     - mongo

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5004:5004"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongo

  # client:
  #   build: ./client
  #   container_name: client
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - api-gateway

volumes:
  mongo_data:
